name: build
on:

  push:
    branches: [ 1 ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Start Build
        run: |
          cd ${{ github.workspace }}
